In [1]:
import matplotlib
%matplotlib tk
%autosave 180
%load_ext autoreload
%autoreload 2

import numpy as np
import datetime
import cv2
import time

import sounddevice as sd
import matplotlib.pyplot as plt
import sox
import scipy, scipy.io.wavfile

import sys
# the mock-0.3.1 dir contains testcase.py, testutils.py & mock.py
sys.path.append('/home/cat/Downloads/spinnaker_python-1.27.0.48-Ubuntu18.04-cp37-cp37m-linux_x86_64/Examples/Python3/')

import PySpin
from Specgram.Specgram import Specgram
from playsound import playsound
import simpleaudio as sa



Autosaving every 180 seconds


In [2]:
def get_isi(P):

    data = P
    data = data.sum(0)-data.sum(0).mean(0)

    scale = P.shape[1]/200.
    t=np.arange(P.shape[1])/200.

    # find peaks
    thresh = 18000
    idx = np.where(data>thresh)[0]
    idx_corrected=[]
    idx_corrected.append(idx[0])
    for k in range(1, idx.shape[0], 1):
        if idx[k]-idx[k-1]>5:
            idx_corrected.append(idx[k])

    idx = np.array(idx_corrected)

    # find peaks that different various amounts
    diffs = idx[1:]-idx[:-1]
    print (diffs.shape)

    # look for thresholds that are bigger than some minmum width; 
    idx2 = np.where(np.logical_and(diffs!=200,diffs>3,diffs!=199))[0]
    print (diffs[idx2])

    #ax=plt.subplot(211)
    print (idx[idx2+1]/200.)

    return idx[idx2+1]/200.

# LOAD DATA SETS
fnames = np.loadtxt('/home/cat/file_list.txt',dtype=np.str)
times = []
ctr = 0
for fname in fnames:
    audio_rec = np.load(fname).squeeze()
    print (ctr, audio_rec.shape)
    #print (type(audio_rec[0]))
    times.append([])
    for ctr_idx, k in enumerate(range(0, audio_rec.shape[0],audio_rec.shape[0]//10)):
        snippit = audio_rec[k:k+audio_rec.shape[0]//10]
        P, extent = Specgram(data = snippit, 
                             sampfreq = 384000, 
                         p0=-300, f0=0.1, f1=64000, 
                         width=0.01, tres = 0.005)

        time = get_isi(P)
        times[ctr].extend(time+ctr_idx*360)
        print (ctr_idx, time+ctr_idx*360)
    print (times)
    ctr+=1
    print ("")
    print ("")
    
print ("DONE MAKING SPEGRAMS")
np.save('/home/cat/may_8_times_3600.npy', times)


(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[11949 11999 11994 12002]
[120.035 180.03  240.    300.01 ]
0 [120.035 180.03  240.    300.01 ]
Computing regular fft specgram
(5,)
[12002 11999 12002 12002 12002]
[ 60.03  120.025 180.035 240.045 300.055]
1 [420.03  480.025 540.035 600.045 660.055]
Computing regular fft specgram
(5,)
[11999 12002 11997 12002 12003]
[ 60.06  120.07  180.055 240.065 300.08 ]
2 [ 780.06   840.07   900.055  960.065 1020.08 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 11997]
[ 60.1   120.11  180.12  240.13  300.115]
3 [1140.1   1200.11  1260.12  1320.13  1380.115]
Computing regular fft specgram
(5,)
[12002 12002 12002 11995 12002]
[ 60.14  120.15  180.16  240.135 300.145]
4 [1500.14  1560.15  1620.16  1680.135 1740.145]
Computing regular fft specgram
(5,)
[11998 12002 11994 12002 12002]
[ 60.145 120.155 180.125 240.135 300.145]
5 [1860.145 1920.155 1980.125 2040.135 2100.145]
Computing regular fft specgram
(5,)
[120

(5,)
[12002 11998 12002 12002 12003]
[ 60.655 120.645 180.655 240.665 300.68 ]
3 [1140.655 1200.645 1260.655 1320.665 1380.68 ]
Computing regular fft specgram
(5,)
[11997 12002 12002 12002 12002]
[ 60.675 120.685 180.695 240.705 300.715]
4 [1500.675 1560.685 1620.695 1680.705 1740.715]
Computing regular fft specgram
(5,)
[12002 12002 12002 12003 12002]
[ 60.72  120.73  180.74  240.755 300.765]
5 [1860.72  1920.73  1980.74  2040.755 2100.765]
Computing regular fft specgram
(5,)
[12002 12003 11998 12002 11999]
[ 60.765 120.78  180.77  240.78  300.775]
6 [2220.765 2280.78  2340.77  2400.78  2460.775]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12003]
[ 60.795 120.805 180.815 240.825 300.84 ]
7 [2580.795 2640.805 2700.815 2760.825 2820.84 ]
Computing regular fft specgram
(5,)
[12002 12002 11998 11984 11991]
[ 60.86  120.87  180.86  240.78  300.735]
8 [2940.86  3000.87  3060.86  3120.78  3180.735]
Computing regular fft specgram
(5,)
[11992 11976 11989 11995 11993]
[ 60.675 

Computing regular fft specgram
(5,)
[12002 12002 11997 11974 12002]
[ 60.72  120.73  180.715 240.585 300.595]
8 [2940.72  3000.73  3060.715 3120.585 3180.595]
Computing regular fft specgram
(5,)
[11996 11996 11991 11999 11999]
[ 60.55  120.53  180.485 240.48  300.475]
9 [3300.55  3360.53  3420.485 3480.48  3540.475]
[[120.035, 180.03, 240.0, 300.01, 420.03, 480.025, 540.035, 600.045, 660.0550000000001, 780.06, 840.0699999999999, 900.0550000000001, 960.065, 1020.0799999999999, 1140.1, 1200.11, 1260.12, 1320.13, 1380.115, 1500.14, 1560.15, 1620.16, 1680.135, 1740.145, 1860.145, 1920.155, 1980.125, 2040.135, 2100.145, 2220.17, 2280.145, 2340.155, 2400.165, 2460.175, 2580.18, 2640.19, 2700.2, 2760.21, 2820.2, 2940.185, 3000.195, 3060.205, 3120.215, 3180.225, 3300.215, 3360.225, 3420.235, 3480.245, 3540.24], [120.57, 180.555, 240.565, 300.575, 420.6, 480.61, 540.62, 600.63, 660.64, 780.64, 840.65, 900.66, 960.67, 1020.6800000000001, 1140.68, 1200.69, 1260.7, 1320.71, 1380.72, 1500.725, 1560

Computing regular fft specgram
(4,)
[12002 12002 12002 12002]
[120.545 180.555 240.565 300.575]
0 [120.545 180.555 240.565 300.575]
Computing regular fft specgram
(5,)
[11998 11999 12002 12002 11993]
[ 60.55  120.545 180.555 240.565 300.53 ]
1 [420.55  480.545 540.555 600.565 660.53 ]
Computing regular fft specgram
(5,)
[12002 11999 12002 12002 12002]
[ 60.55  120.545 180.555 240.565 300.575]
2 [ 780.55   840.545  900.555  960.565 1020.575]
Computing regular fft specgram
(5,)
[12002 12002 11998 12002 12002]
[ 60.595 120.605 180.595 240.605 300.615]
3 [1140.595 1200.605 1260.595 1320.605 1380.615]
Computing regular fft specgram
(5,)
[12002 11999 12002 12002 12002]
[ 60.635 120.63  180.64  240.65  300.66 ]
4 [1500.635 1560.63  1620.64  1680.65  1740.66 ]
Computing regular fft specgram
(5,)
[11999 11999 12002 11998 12002]
[ 60.665 120.66  180.67  240.66  300.67 ]
5 [1860.665 1920.66  1980.67  2040.66  2100.67 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 11998 11999]
[ 60.675 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12003 12002]
[120.59  180.6   240.615 300.625]
0 [120.59  180.6   240.615 300.625]
Computing regular fft specgram
(5,)
[12002 12002 12003 12002 11998]
[ 60.625 120.635 180.65  240.66  300.65 ]
1 [420.625 480.635 540.65  600.66  660.65 ]
Computing regular fft specgram
(5,)
[12003 12002 12002 11998 12002]
[ 60.675 120.685 180.695 240.685 300.695]
2 [ 780.675  840.685  900.695  960.685 1020.695]
Computing regular fft specgram
(5,)
[12002 12002 11997 12002 12002]
[ 60.72  120.73  180.715 240.725 300.735]
3 [1140.72  1200.73  1260.715 1320.725 1380.735]
Computing regular fft specgram
(5,)
[12003 11995 12002 12002 12002]
[ 60.76  120.735 180.745 240.755 300.765]
4 [1500.76  1560.735 1620.745 1680.755 1740.765]
Computing regular fft specgram
(5,)
[11996 12002 12002 12002 12002]
[ 60.755 120.765 180.775 240.785 300.795]
5 [1860.755 1920.765 1980.775 2040.785 2100.795]
Computing regular fft specgram
(5,)
[119

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 11998]
[120.585 180.595 240.605 300.595]
0 [120.585 180.595 240.605 300.595]
Computing regular fft specgram
(5,)
[12002 12002 12002 11999 11998]
[ 60.6   120.61  180.62  240.615 300.605]
1 [420.6   480.61  540.62  600.615 660.605]
Computing regular fft specgram
(5,)
[12002 12003 12002 12002 12002]
[ 60.625 120.64  180.65  240.66  300.67 ]
2 [ 780.625  840.64   900.65   960.66  1020.67 ]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 12002]
[ 60.69  120.7   180.695 240.705 300.715]
3 [1140.69  1200.7   1260.695 1320.705 1380.715]
Computing regular fft specgram
(5,)
[12002 12002 12003 12002 12002]
[ 60.735 120.745 180.76  240.77  300.78 ]
4 [1500.735 1560.745 1620.76  1680.77  1740.78 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.8  120.81 180.82 240.83 300.84]
5 [1860.8  1920.81 1980.82 2040.83 2100.84]
Computing regular fft specgram
(5,)
[11999 12002 1

Computing regular fft specgram
(5,)
[11997 12002 12003 12002 12002]
[ 60.66  120.67  180.685 240.695 300.705]
6 [2220.66  2280.67  2340.685 2400.695 2460.705]
Computing regular fft specgram
(5,)
[12002 12002 11999 11997 12002]
[ 60.725 120.735 180.73  240.715 300.725]
7 [2580.725 2640.735 2700.73  2760.715 2820.725]
Computing regular fft specgram
(5,)
[12003 12002 12002 11986 11992]
[ 60.75 120.76 180.77 240.7  300.66]
8 [2940.75 3000.76 3060.77 3120.7  3180.66]
Computing regular fft specgram
(5,)
[11990 11990 11980 12002 11996]
[ 60.57 120.52 180.42 240.43 300.41]
9 [3300.57 3360.52 3420.42 3480.43 3540.41]
[[120.035, 180.03, 240.0, 300.01, 420.03, 480.025, 540.035, 600.045, 660.0550000000001, 780.06, 840.0699999999999, 900.0550000000001, 960.065, 1020.0799999999999, 1140.1, 1200.11, 1260.12, 1320.13, 1380.115, 1500.14, 1560.15, 1620.16, 1680.135, 1740.145, 1860.145, 1920.155, 1980.125, 2040.135, 2100.145, 2220.17, 2280.145, 2340.155, 2400.165, 2460.175, 2580.18, 2640.19, 2700.2, 2760

Computing regular fft specgram
(5,)
[11993 11986 11983 11991 11996]
[ 60.74  120.67  180.585 240.54  300.52 ]
9 [3300.74  3360.67  3420.585 3480.54  3540.52 ]
[[120.035, 180.03, 240.0, 300.01, 420.03, 480.025, 540.035, 600.045, 660.0550000000001, 780.06, 840.0699999999999, 900.0550000000001, 960.065, 1020.0799999999999, 1140.1, 1200.11, 1260.12, 1320.13, 1380.115, 1500.14, 1560.15, 1620.16, 1680.135, 1740.145, 1860.145, 1920.155, 1980.125, 2040.135, 2100.145, 2220.17, 2280.145, 2340.155, 2400.165, 2460.175, 2580.18, 2640.19, 2700.2, 2760.21, 2820.2, 2940.185, 3000.195, 3060.205, 3120.215, 3180.225, 3300.215, 3360.225, 3420.235, 3480.245, 3540.24], [120.57, 180.555, 240.565, 300.575, 420.6, 480.61, 540.62, 600.63, 660.64, 780.64, 840.65, 900.66, 960.67, 1020.6800000000001, 1140.68, 1200.69, 1260.7, 1320.71, 1380.72, 1500.725, 1560.735, 1620.745, 1680.7350000000001, 1740.745, 1860.765, 1920.775, 1980.785, 2040.795, 2100.805, 2220.825, 2280.835, 2340.85, 2400.86, 2460.8450000000003, 2580.

Computing regular fft specgram
(5,)
[11998 12002 11992 11988 12002]
[ 60.82 120.83 180.79 240.73 300.74]
9 [3300.82 3360.83 3420.79 3480.73 3540.74]
[[120.035, 180.03, 240.0, 300.01, 420.03, 480.025, 540.035, 600.045, 660.0550000000001, 780.06, 840.0699999999999, 900.0550000000001, 960.065, 1020.0799999999999, 1140.1, 1200.11, 1260.12, 1320.13, 1380.115, 1500.14, 1560.15, 1620.16, 1680.135, 1740.145, 1860.145, 1920.155, 1980.125, 2040.135, 2100.145, 2220.17, 2280.145, 2340.155, 2400.165, 2460.175, 2580.18, 2640.19, 2700.2, 2760.21, 2820.2, 2940.185, 3000.195, 3060.205, 3120.215, 3180.225, 3300.215, 3360.225, 3420.235, 3480.245, 3540.24], [120.57, 180.555, 240.565, 300.575, 420.6, 480.61, 540.62, 600.63, 660.64, 780.64, 840.65, 900.66, 960.67, 1020.6800000000001, 1140.68, 1200.69, 1260.7, 1320.71, 1380.72, 1500.725, 1560.735, 1620.745, 1680.7350000000001, 1740.745, 1860.765, 1920.775, 1980.785, 2040.795, 2100.805, 2220.825, 2280.835, 2340.85, 2400.86, 2460.8450000000003, 2580.865, 2640.

Computing regular fft specgram
(5,)
[12002 12002 12002 11999 11998]
[ 60.815 120.825 180.835 240.83  300.82 ]
6 [2220.815 2280.825 2340.835 2400.83  2460.82 ]
Computing regular fft specgram
(5,)
[12002 12002 12003 12002 12002]
[ 60.84  120.85  180.865 240.875 300.885]
7 [2580.84  2640.85  2700.865 2760.875 2820.885]
Computing regular fft specgram
(5,)
[12002 12002 12002 11996 11983]
[ 60.905 120.915 180.925 240.905 300.82 ]
8 [2940.905 3000.915 3060.925 3120.905 3180.82 ]
Computing regular fft specgram
(5,)
[11981 11985 11986 12002 11979]
[ 60.63  120.555 180.485 240.495 300.39 ]
9 [3300.63  3360.555 3420.485 3480.495 3540.39 ]
[[120.035, 180.03, 240.0, 300.01, 420.03, 480.025, 540.035, 600.045, 660.0550000000001, 780.06, 840.0699999999999, 900.0550000000001, 960.065, 1020.0799999999999, 1140.1, 1200.11, 1260.12, 1320.13, 1380.115, 1500.14, 1560.15, 1620.16, 1680.135, 1740.145, 1860.145, 1920.155, 1980.125, 2040.135, 2100.145, 2220.17, 2280.145, 2340.155, 2400.165, 2460.175, 2580.18, 2

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 11994]
[120.58 180.59 240.6  300.57]
0 [120.58 180.59 240.6  300.57]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.59 120.6  180.61 240.62 300.63]
1 [420.59 480.6  540.61 600.62 660.63]
Computing regular fft specgram
(5,)
[11999 11999 11999 11999 12002]
[ 60.635 120.63  180.625 240.62  300.63 ]
2 [ 780.635  840.63   900.625  960.62  1020.63 ]
Computing regular fft specgram
(5,)
[11998 12003 12002 12002 12002]
[ 60.63  120.645 180.655 240.665 300.675]
3 [1140.63  1200.645 1260.655 1320.665 1380.675]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.695 120.705 180.715 240.725 300.735]
4 [1500.695 1560.705 1620.715 1680.725 1740.735]
Computing regular fft specgram
(5,)
[12002 11997 12003 12002 12002]
[ 60.735 120.72  180.735 240.745 300.755]
5 [1860.735 1920.72  1980.735 2040.745 2100.755]
Computing regular fft specgram
(5,)
[12002 12002 12002 119

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 11998 12002]
[120.58 180.59 240.58 300.59]
0 [120.58 180.59 240.58 300.59]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 11999]
[ 60.595 120.605 180.615 240.625 300.62 ]
1 [420.595 480.605 540.615 600.625 660.62 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 11994 12002]
[ 60.595 120.605 180.615 240.585 300.595]
2 [ 780.595  840.605  900.615  960.585 1020.595]
Computing regular fft specgram
(5,)
[12002 12002 11997 12002 12002]
[ 60.62  120.63  180.615 240.625 300.635]
3 [1140.62  1200.63  1260.615 1320.625 1380.635]
Computing regular fft specgram
(5,)
[12003 11997 12002 12002 12002]
[ 60.66  120.645 180.655 240.665 300.675]
4 [1500.66  1560.645 1620.655 1680.665 1740.675]
Computing regular fft specgram
(5,)
[11999 12002 12002 12002 12002]
[ 60.68 120.69 180.7  240.71 300.72]
5 [1860.68 1920.69 1980.7  2040.71 2100.72]
Computing regular fft specgram
(5,)
[11999 12002 12002 120

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 11999 12002 11993]
[120.58  180.575 240.585 300.55 ]
0 [120.58  180.575 240.585 300.55 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 11993 12002]
[ 60.57  120.58  180.59  240.555 300.565]
1 [420.57  480.58  540.59  600.555 660.565]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 12002]
[ 60.585 120.595 180.59  240.6   300.61 ]
2 [ 780.585  840.595  900.59   960.6   1020.61 ]
Computing regular fft specgram
(5,)
[12003 11996 12002 12002 12002]
[ 60.635 120.615 180.625 240.635 300.645]
3 [1140.635 1200.615 1260.625 1320.635 1380.645]
Computing regular fft specgram
(5,)
[11998 12002 12002 12003 12002]
[ 60.585 120.595 180.605 240.62  300.63 ]
4 [1500.585 1560.595 1620.605 1680.62  1740.63 ]
Computing regular fft specgram
(5,)
[12002 11998 12002 12002 12002]
[ 60.625 120.615 180.625 240.635 300.645]
5 [1860.625 1920.615 1980.625 2040.635 2100.645]
Computing regular fft specgram
(5,)
[120

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 11993 12002 12002]
[120.55  180.515 240.525 300.535]
0 [120.55  180.515 240.525 300.535]
Computing regular fft specgram
(5,)
[12002 11998 12002 12002 11994]
[ 60.54 120.53 180.54 240.55 300.52]
1 [420.54 480.53 540.54 600.55 660.52]
Computing regular fft specgram
(5,)
[12002 12002 12002 11998 11997]
[ 60.54  120.55  180.56  240.55  300.535]
2 [ 780.54   840.55   900.56   960.55  1020.535]
Computing regular fft specgram
(5,)
[12002 12002 11999 11998 11998]
[ 60.535 120.545 180.54  240.53  300.52 ]
3 [1140.535 1200.545 1260.54  1320.53  1380.52 ]
Computing regular fft specgram
(5,)
[12002 12002 11998 12002 12002]
[ 60.54 120.55 180.54 240.55 300.56]
4 [1500.54 1560.55 1620.54 1680.55 1740.56]
Computing regular fft specgram
(5,)
[12002 11998 12002 11997 11998]
[ 60.58  120.57  180.58  240.565 300.555]
5 [1860.58  1920.57  1980.58  2040.565 2100.555]
Computing regular fft specgram
(5,)
[12002 12003 12002 12002

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 11998 12002 11999]
[120.585 180.575 240.585 300.58 ]
0 [120.585 180.575 240.585 300.58 ]
Computing regular fft specgram
(5,)
[12002 11998 12003 12002 12002]
[ 60.6   120.59  180.605 240.615 300.625]
1 [420.6   480.59  540.605 600.615 660.625]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 12002]
[ 60.645 120.655 180.65  240.66  300.67 ]
2 [ 780.645  840.655  900.65   960.66  1020.67 ]
Computing regular fft specgram
(5,)
[12002 11998 12002 12002 12002]
[ 60.69 120.68 180.69 240.7  300.71]
3 [1140.69 1200.68 1260.69 1320.7  1380.71]
Computing regular fft specgram
(5,)
[11999 12002 12002 12002 12002]
[ 60.715 120.725 180.735 240.745 300.755]
4 [1500.715 1560.725 1620.735 1680.745 1740.755]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.755 120.765 180.775 240.785 300.795]
5 [1860.755 1920.765 1980.775 2040.785 2100.795]
Computing regular fft specgram
(5,)
[12003 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[11998 12002 12002 12002]
[120.565 180.575 240.585 300.595]
0 [120.565 180.575 240.585 300.595]
Computing regular fft specgram
(5,)
[11998 12002 12002 12002 12003]
[ 60.6   120.61  180.62  240.63  300.645]
1 [420.6   480.61  540.62  600.63  660.645]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.665 120.675 180.685 240.695 300.705]
2 [ 780.665  840.675  900.685  960.695 1020.705]
Computing regular fft specgram
(5,)
[12002 12002 12002 11994 12002]
[ 60.725 120.735 180.745 240.715 300.725]
3 [1140.725 1200.735 1260.745 1320.715 1380.725]
Computing regular fft specgram
(5,)
[12002 12002 11994 12002 11997]
[ 60.75  120.76  180.73  240.74  300.725]
4 [1500.75  1560.76  1620.73  1680.74  1740.725]
Computing regular fft specgram
(5,)
[12002 11998 12002 12002 12003]
[ 60.75  120.74  180.75  240.76  300.775]
5 [1860.75  1920.74  1980.75  2040.76  2100.775]
Computing regular fft specgram
(5,)
[119

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 11999]
[120.585 180.595 240.605 300.6  ]
0 [120.585 180.595 240.605 300.6  ]
Computing regular fft specgram
(5,)
[12002 12002 12002 11999 12002]
[ 60.62  120.63  180.64  240.635 300.645]
1 [420.62  480.63  540.64  600.635 660.645]
Computing regular fft specgram
(5,)
[12002 11998 11998 12003 12002]
[ 60.665 120.655 180.645 240.66  300.67 ]
2 [ 780.665  840.655  900.645  960.66  1020.67 ]
Computing regular fft specgram
(5,)
[12002 11999 12002 12002 12002]
[ 60.69  120.685 180.695 240.705 300.715]
3 [1140.69  1200.685 1260.695 1320.705 1380.715]
Computing regular fft specgram
(5,)
[11994 12002 12002 12002 12002]
[ 60.695 120.705 180.715 240.725 300.735]
4 [1500.695 1560.705 1620.715 1680.725 1740.735]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 11998]
[ 60.74 120.75 180.76 240.77 300.76]
5 [1860.74 1920.75 1980.76 2040.77 2100.76]
Computing regular fft specgram
(5,)
[11998 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 11997 12002]
[120.55  180.56  240.545 300.555]
0 [120.55  180.56  240.545 300.555]
Computing regular fft specgram
(5,)
[12003 12002 11997 12002 12002]
[ 60.58  120.59  180.575 240.585 300.595]
1 [420.58  480.59  540.575 600.585 660.595]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 11998]
[ 60.6  120.61 180.62 240.63 300.62]
2 [ 780.6   840.61  900.62  960.63 1020.62]
Computing regular fft specgram
(5,)
[12002 12002 12002 11998 11997]
[ 60.64  120.65  180.66  240.65  300.635]
3 [1140.64  1200.65  1260.66  1320.65  1380.635]
Computing regular fft specgram
(5,)
[12002 12003 11998 12002 12002]
[ 60.655 120.67  180.66  240.67  300.68 ]
4 [1500.655 1560.67  1620.66  1680.67  1740.68 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.705 120.715 180.725 240.735 300.745]
5 [1860.705 1920.715 1980.725 2040.735 2100.745]
Computing regular fft specgram
(5,)
[11998 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 11999 12002 12002]
[120.59  180.585 240.595 300.605]
0 [120.59  180.585 240.595 300.605]
Computing regular fft specgram
(5,)
[12002 11999 12002 12002 12002]
[ 60.625 120.62  180.63  240.64  300.65 ]
1 [420.625 480.62  540.63  600.64  660.65 ]
Computing regular fft specgram
(5,)
[12002 11999 12002 12002 12002]
[ 60.67  120.665 180.675 240.685 300.695]
2 [ 780.67   840.665  900.675  960.685 1020.695]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.695 120.705 180.715 240.725 300.735]
3 [1140.695 1200.705 1260.715 1320.725 1380.735]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.76 120.77 180.78 240.79 300.8 ]
4 [1500.76 1560.77 1620.78 1680.79 1740.8 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12003]
[ 60.82  120.83  180.84  240.85  300.865]
5 [1860.82  1920.83  1980.84  2040.85  2100.865]
Computing regular fft specgram
(5,)
[12002 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12002]
[120.575 180.585 240.595 300.605]
0 [120.575 180.585 240.595 300.605]
Computing regular fft specgram
(5,)
[11998 12002 12002 12002 12002]
[ 60.605 120.615 180.625 240.635 300.645]
1 [420.605 480.615 540.625 600.635 660.645]
Computing regular fft specgram
(5,)
[12002 11998 11999 12002 12002]
[ 60.665 120.655 180.65  240.66  300.67 ]
2 [ 780.665  840.655  900.65   960.66  1020.67 ]
Computing regular fft specgram
(5,)
[12002 11979 11996 12002 12002]
[ 60.665 120.56  180.54  240.55  300.56 ]
3 [1140.665 1200.56  1260.54  1320.55  1380.56 ]
Computing regular fft specgram
(5,)
[12002 12003 12002 12002 12002]
[ 60.58  120.595 180.605 240.615 300.625]
4 [1500.58  1560.595 1620.605 1680.615 1740.625]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.605 120.615 180.625 240.635 300.645]
5 [1860.605 1920.615 1980.625 2040.635 2100.645]
Computing regular fft specgram
(5,)
[120

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 11997]
[120.585 180.595 240.605 300.59 ]
0 [120.585 180.595 240.605 300.59 ]
Computing regular fft specgram
(5,)
[12002 11999 12002 12002 12002]
[ 60.595 120.59  180.6   240.61  300.62 ]
1 [420.595 480.59  540.6   600.61  660.62 ]
Computing regular fft specgram
(5,)
[12002 12003 12002 12002 11997]
[ 60.64  120.655 180.665 240.675 300.66 ]
2 [ 780.64   840.655  900.665  960.675 1020.66 ]
Computing regular fft specgram
(5,)
[11999 12002 12002 12002 12002]
[ 60.665 120.675 180.685 240.695 300.705]
3 [1140.665 1200.675 1260.685 1320.695 1380.705]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.73 120.74 180.75 240.76 300.77]
4 [1500.73 1560.74 1620.75 1680.76 1740.77]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12003]
[ 60.79  120.8   180.81  240.82  300.835]
5 [1860.79  1920.8   1980.81  2040.82  2100.835]
Computing regular fft specgram
(5,)
[12002 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[11998 11998 12002 12002]
[120.565 180.555 240.565 300.575]
0 [120.565 180.555 240.565 300.575]
Computing regular fft specgram
(5,)
[11998 12002 12002 12002 12002]
[ 60.575 120.585 180.595 240.605 300.615]
1 [420.575 480.585 540.595 600.605 660.615]
Computing regular fft specgram
(5,)
[12003 12002 12002 12002 11998]
[ 60.605 120.615 180.625 240.635 300.625]
2 [ 780.605  840.615  900.625  960.635 1020.625]
Computing regular fft specgram
(5,)
[12002 12002 12002 11994 12002]
[ 60.65 120.66 180.67 240.64 300.65]
3 [1140.65 1200.66 1260.67 1320.64 1380.65]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 11998]
[ 60.67  120.68  180.675 240.685 300.675]
4 [1500.67  1560.68  1620.675 1680.685 1740.675]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.695 120.705 180.715 240.725 300.735]
5 [1860.695 1920.705 1980.715 2040.725 2100.735]
Computing regular fft specgram
(5,)
[11999 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12002]
[120.58 180.59 240.6  300.61]
0 [120.58 180.59 240.6  300.61]
Computing regular fft specgram
(5,)
[12002 12002 11998 12003 12002]
[ 60.635 120.645 180.635 240.65  300.66 ]
1 [420.635 480.645 540.635 600.65  660.66 ]
Computing regular fft specgram
(5,)
[12002 11997 12002 12002 12003]
[ 60.68  120.665 180.675 240.685 300.7  ]
2 [ 780.68   840.665  900.675  960.685 1020.7  ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.72 120.73 180.74 240.75 300.76]
3 [1140.72 1200.73 1260.74 1320.75 1380.76]
Computing regular fft specgram
(5,)
[12002 11998 12002 12002 12002]
[ 60.78 120.77 180.78 240.79 300.8 ]
4 [1500.78 1560.77 1620.78 1680.79 1740.8 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12003]
[ 60.82  120.83  180.84  240.85  300.865]
5 [1860.82  1920.83  1980.84  2040.85  2100.865]
Computing regular fft specgram
(5,)
[12002 12002 11997 12002 12003]


(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[11999 12002 12002 11996]
[120.55 180.56 240.57 300.55]
0 [120.55 180.56 240.57 300.55]
Computing regular fft specgram
(5,)
[12002 12002 11998 12002 12002]
[ 60.57 120.58 180.57 240.58 300.59]
1 [420.57 480.58 540.57 600.58 660.59]
Computing regular fft specgram
(5,)
[12002 12002 12002 11998 12002]
[ 60.595 120.605 180.615 240.605 300.615]
2 [ 780.595  840.605  900.615  960.605 1020.615]
Computing regular fft specgram
(5,)
[12002 12002 12002 12003 12002]
[ 60.61  120.62  180.63  240.645 300.655]
3 [1140.61  1200.62  1260.63  1320.645 1380.655]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.675 120.685 180.695 240.705 300.715]
4 [1500.675 1560.685 1620.695 1680.705 1740.715]
Computing regular fft specgram
(5,)
[12002 12002 12003 12002 12002]
[ 60.735 120.745 180.76  240.77  300.78 ]
5 [1860.735 1920.745 1980.76  2040.77  2100.78 ]
Computing regular fft specgram
(5,)
[11999 12002 12002 119

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[11998 12002 12002 12002]
[120.53 180.54 240.55 300.56]
0 [120.53 180.54 240.55 300.56]
Computing regular fft specgram
(5,)
[12002 12002 12003 12002 12002]
[ 60.58  120.59  180.605 240.615 300.625]
1 [420.58  480.59  540.605 600.615 660.625]
Computing regular fft specgram
(5,)
[12002 12002 12002 11999 12002]
[ 60.645 120.655 180.665 240.66  300.67 ]
2 [ 780.645  840.655  900.665  960.66  1020.67 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.69 120.7  180.71 240.72 300.73]
3 [1140.69 1200.7  1260.71 1320.72 1380.73]
Computing regular fft specgram
(5,)
[12003 12002 12002 12002 12002]
[ 60.755 120.765 180.775 240.785 300.795]
4 [1500.755 1560.765 1620.775 1680.785 1740.795]
Computing regular fft specgram
(5,)
[12002 12002 12002 11998 11997]
[ 60.815 120.825 180.835 240.825 300.81 ]
5 [1860.815 1920.825 1980.835 2040.825 2100.81 ]
Computing regular fft specgram
(5,)
[12002 12003 12002 119

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12003]
[120.565 180.575 240.585 300.6  ]
0 [120.565 180.575 240.585 300.6  ]
Computing regular fft specgram
(5,)
[11998 12002 12002 12002 12002]
[ 60.55 120.56 180.57 240.58 300.59]
1 [420.55 480.56 540.57 600.58 660.59]
Computing regular fft specgram
(5,)
[12002 12002 12003 12002 11993]
[ 60.57  120.58  180.595 240.605 300.57 ]
2 [ 780.57   840.58   900.595  960.605 1020.57 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.59 120.6  180.61 240.62 300.63]
3 [1140.59 1200.6  1260.61 1320.62 1380.63]
Computing regular fft specgram
(5,)
[12002 12002 12003 12002 12002]
[ 60.65  120.66  180.675 240.685 300.695]
4 [1500.65  1560.66  1620.675 1680.685 1740.695]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 12002]
[ 60.715 120.725 180.72  240.73  300.74 ]
5 [1860.715 1920.725 1980.72  2040.73  2100.74 ]
Computing regular fft specgram
(5,)
[12002 11998 11998 12002

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 11998 12002]
[120.565 180.575 240.565 300.575]
0 [120.565 180.575 240.565 300.575]
Computing regular fft specgram
(5,)
[12002 11998 11998 12002 12002]
[ 60.575 120.565 180.555 240.565 300.575]
1 [420.575 480.565 540.555 600.565 660.575]
Computing regular fft specgram
(5,)
[11998 12002 12002 12002 12002]
[ 60.575 120.585 180.595 240.605 300.615]
2 [ 780.575  840.585  900.595  960.605 1020.615]
Computing regular fft specgram
(5,)
[12002 12003 12002 11997 12002]
[ 60.61  120.625 180.635 240.62  300.63 ]
3 [1140.61  1200.625 1260.635 1320.62  1380.63 ]
Computing regular fft specgram
(5,)
[12002 12003 12002 12002 11995]
[ 60.65  120.665 180.675 240.685 300.66 ]
4 [1500.65  1560.665 1620.675 1680.685 1740.66 ]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 12002]
[ 60.68  120.69  180.685 240.695 300.705]
5 [1860.68  1920.69  1980.685 2040.695 2100.705]
Computing regular fft specgram
(5,)
[120

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[11999 12002 12002 12002]
[120.57 180.58 240.59 300.6 ]
0 [120.57 180.58 240.59 300.6 ]
Computing regular fft specgram
(5,)
[11999 12002 12002 12002 12002]
[ 60.605 120.615 180.625 240.635 300.645]
1 [420.605 480.615 540.625 600.635 660.645]
Computing regular fft specgram
(5,)
[11998 12002 12002 12002 11999]
[ 60.63  120.64  180.65  240.66  300.655]
2 [ 780.63   840.64   900.65   960.66  1020.655]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 11998]
[ 60.675 120.685 180.695 240.705 300.695]
3 [1140.675 1200.685 1260.695 1320.705 1380.695]
Computing regular fft specgram
(5,)
[12002 12002 12002 11997 11998]
[ 60.715 120.725 180.735 240.72  300.71 ]
4 [1500.715 1560.725 1620.735 1680.72  1740.71 ]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 12002]
[ 60.73  120.74  180.735 240.745 300.755]
5 [1860.73  1920.74  1980.735 2040.745 2100.755]
Computing regular fft specgram
(5,)
[12002 11999

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 11998 12002 12002]
[120.545 180.535 240.545 300.555]
0 [120.545 180.535 240.545 300.555]
Computing regular fft specgram
(5,)
[12002 11998 12002 12002 12002]
[ 60.575 120.565 180.575 240.585 300.595]
1 [420.575 480.565 540.575 600.585 660.595]
Computing regular fft specgram
(5,)
[12002 11997 12003 12002 12002]
[ 60.595 120.58  180.595 240.605 300.615]
2 [ 780.595  840.58   900.595  960.605 1020.615]
Computing regular fft specgram
(5,)
[11999 12002 12002 12002 12002]
[ 60.62 120.63 180.64 240.65 300.66]
3 [1140.62 1200.63 1260.64 1320.65 1380.66]
Computing regular fft specgram
(5,)
[12002 12002 12002 12003 11997]
[ 60.68  120.69  180.7   240.715 300.7  ]
4 [1500.68  1560.69  1620.7   1680.715 1740.7  ]
Computing regular fft specgram
(5,)
[11997 12002 12002 11998 12002]
[ 60.675 120.685 180.695 240.685 300.695]
5 [1860.675 1920.685 1980.695 2040.685 2100.695]
Computing regular fft specgram
(5,)
[12002 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[11998 12002 12002 12002]
[120.55 180.56 240.57 300.58]
0 [120.55 180.56 240.57 300.58]
Computing regular fft specgram
(5,)
[12002 11998 12002 12002 12002]
[ 60.6  120.59 180.6  240.61 300.62]
1 [420.6  480.59 540.6  600.61 660.62]
Computing regular fft specgram
(5,)
[12002 11998 12002 12002 12002]
[ 60.64 120.63 180.64 240.65 300.66]
2 [ 780.64  840.63  900.64  960.65 1020.66]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 11998]
[ 60.665 120.675 180.685 240.695 300.685]
3 [1140.665 1200.675 1260.685 1320.695 1380.685]
Computing regular fft specgram
(5,)
[12002 12002 12002 11993 12002]
[ 60.705 120.715 180.725 240.69  300.7  ]
4 [1500.705 1560.715 1620.725 1680.69  1740.7  ]
Computing regular fft specgram
(5,)
[12003 12002 11998 12002 12002]
[ 60.725 120.735 180.725 240.735 300.745]
5 [1860.725 1920.735 1980.725 2040.735 2100.745]
Computing regular fft specgram
(5,)
[11997 12002 12002 12002 12002]


(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12002]
[120.59 180.6  240.61 300.62]
0 [120.59 180.6  240.61 300.62]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 12002]
[ 60.64  120.65  180.645 240.655 300.665]
1 [420.64  480.65  540.645 600.655 660.665]
Computing regular fft specgram
(5,)
[12002 12003 12002 12002 12002]
[ 60.685 120.7   180.71  240.72  300.73 ]
2 [ 780.685  840.7    900.71   960.72  1020.73 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.75 120.76 180.77 240.78 300.79]
3 [1140.75 1200.76 1260.77 1320.78 1380.79]
Computing regular fft specgram
(5,)
[12003 11997 12002 12002 11998]
[ 60.815 120.8   180.81  240.82  300.81 ]
4 [1500.815 1560.8   1620.81  1680.82  1740.81 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.83 120.84 180.85 240.86 300.87]
5 [1860.83 1920.84 1980.85 2040.86 2100.87]
Computing regular fft specgram
(5,)
[12002 12003 11997 12002 12002]


(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12003]
[120.54  180.55  240.56  300.575]
0 [120.54  180.55  240.56  300.575]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.595 120.605 180.615 240.625 300.635]
1 [420.595 480.605 540.615 600.625 660.635]
Computing regular fft specgram
(5,)
[12002 12002 11998 12002 12002]
[ 60.655 120.665 180.655 240.665 300.675]
2 [ 780.655  840.665  900.655  960.665 1020.675]
Computing regular fft specgram
(5,)
[12002 12002 12002 12003 12002]
[ 60.695 120.705 180.715 240.73  300.74 ]
3 [1140.695 1200.705 1260.715 1320.73  1380.74 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.76 120.77 180.78 240.79 300.8 ]
4 [1500.76 1560.77 1620.78 1680.79 1740.8 ]
Computing regular fft specgram
(5,)
[12002 11997 12002 12002 12002]
[ 60.82  120.805 180.815 240.825 300.835]
5 [1860.82  1920.805 1980.815 2040.825 2100.835]
Computing regular fft specgram
(5,)
[12002 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12003 11998 12002]
[120.555 180.57  240.56  300.57 ]
0 [120.555 180.57  240.56  300.57 ]
Computing regular fft specgram
(5,)
[12003 12002 11995 12002 12002]
[ 60.595 120.605 180.58  240.59  300.6  ]
1 [420.595 480.605 540.58  600.59  660.6  ]
Computing regular fft specgram
(5,)
[12002 12003 12002 12002 12002]
[ 60.62  120.635 180.645 240.655 300.665]
2 [ 780.62   840.635  900.645  960.655 1020.665]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.645 120.655 180.665 240.675 300.685]
3 [1140.645 1200.655 1260.665 1320.675 1380.685]
Computing regular fft specgram
(5,)
[12003 12002 12002 12002 11999]
[ 60.71  120.72  180.73  240.74  300.735]
4 [1500.71  1560.72  1620.73  1680.74  1740.735]
Computing regular fft specgram
(5,)
[12002 12002 12002 11999 12002]
[ 60.755 120.765 180.775 240.77  300.78 ]
5 [1860.755 1920.765 1980.775 2040.77  2100.78 ]
Computing regular fft specgram
(5,)
[120

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12003 12002 12002]
[120.545 180.56  240.57  300.58 ]
0 [120.545 180.56  240.57  300.58 ]
Computing regular fft specgram
(5,)
[12002 11998 12003 12002 12002]
[ 60.6   120.59  180.605 240.615 300.625]
1 [420.6   480.59  540.605 600.615 660.625]
Computing regular fft specgram
(5,)
[11997 12002 12002 12003 12002]
[ 60.62  120.63  180.64  240.655 300.665]
2 [ 780.62   840.63   900.64   960.655 1020.665]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.685 120.695 180.705 240.715 300.725]
3 [1140.685 1200.695 1260.705 1320.715 1380.725]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 12002]
[ 60.745 120.755 180.75  240.76  300.77 ]
4 [1500.745 1560.755 1620.75  1680.76  1740.77 ]
Computing regular fft specgram
(5,)
[11999 12002 12002 12002 12002]
[ 60.775 120.785 180.795 240.805 300.815]
5 [1860.775 1920.785 1980.795 2040.805 2100.815]
Computing regular fft specgram
(5,)
[120

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12002]
[120.59 180.6  240.61 300.62]
0 [120.59 180.6  240.61 300.62]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.64 120.65 180.66 240.67 300.68]
1 [420.64 480.65 540.66 600.67 660.68]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.705 120.715 180.725 240.735 300.745]
2 [ 780.705  840.715  900.725  960.735 1020.745]
Computing regular fft specgram
(5,)
[11996 12002 12002 12002 12002]
[ 60.735 120.745 180.755 240.765 300.775]
3 [1140.735 1200.745 1260.755 1320.765 1380.775]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 11999]
[ 60.795 120.805 180.815 240.825 300.82 ]
4 [1500.795 1560.805 1620.815 1680.825 1740.82 ]
Computing regular fft specgram
(5,)
[12003 12002 12002 12002 12002]
[ 60.845 120.855 180.865 240.875 300.885]
5 [1860.845 1920.855 1980.865 2040.875 2100.885]
Computing regular fft specgram
(5,)
[12002 11981 12002 119

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 11998 12003 12002]
[120.57  180.56  240.575 300.585]
0 [120.57  180.56  240.575 300.585]
Computing regular fft specgram
(5,)
[12002 11998 12003 12002 12002]
[ 60.605 120.595 180.61  240.62  300.63 ]
1 [420.605 480.595 540.61  600.62  660.63 ]
Computing regular fft specgram
(5,)
[12002 12002 11998 12002 12002]
[ 60.625 120.635 180.625 240.635 300.645]
2 [ 780.625  840.635  900.625  960.635 1020.645]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.65 120.66 180.67 240.68 300.69]
3 [1140.65 1200.66 1260.67 1320.68 1380.69]
Computing regular fft specgram
(5,)
[12002 12002 12003 11998 12002]
[ 60.71  120.72  180.735 240.725 300.735]
4 [1500.71  1560.72  1620.735 1680.725 1740.735]
Computing regular fft specgram
(5,)
[12003 12002 11993 12002 12002]
[ 60.76  120.77  180.735 240.745 300.755]
5 [1860.76  1920.77  1980.735 2040.745 2100.755]
Computing regular fft specgram
(5,)
[12002 11992 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12000 12002]
[120.58 180.59 240.59 300.6 ]
0 [120.58 180.59 240.59 300.6 ]
Computing regular fft specgram
(5,)
[12003 12002 12002 12002 12002]
[ 60.625 120.635 180.645 240.655 300.665]
1 [420.625 480.635 540.645 600.655 660.665]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.685 120.695 180.705 240.715 300.725]
2 [ 780.685  840.695  900.705  960.715 1020.725]
Computing regular fft specgram
(5,)
[11998 12002 12002 12003 12002]
[ 60.73  120.74  180.75  240.765 300.775]
3 [1140.73  1200.74  1260.75  1320.765 1380.775]
Computing regular fft specgram
(5,)
[12002 12002 11997 12003 12002]
[ 60.795 120.805 180.79  240.805 300.815]
4 [1500.795 1560.805 1620.79  1680.805 1740.815]
Computing regular fft specgram
(5,)
[12002 12002 12002 11999 11998]
[ 60.835 120.845 180.855 240.85  300.84 ]
5 [1860.835 1920.845 1980.855 2040.85  2100.84 ]
Computing regular fft specgram
(5,)
[12002 11996

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[11998 11998 12002 12003]
[120.56  180.55  240.56  300.575]
0 [120.56  180.55  240.56  300.575]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.595 120.605 180.615 240.625 300.635]
1 [420.595 480.605 540.615 600.625 660.635]
Computing regular fft specgram
(5,)
[12002 12002 12002 12003 12002]
[ 60.655 120.665 180.675 240.69  300.7  ]
2 [ 780.655  840.665  900.675  960.69  1020.7  ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.72 120.73 180.74 240.75 300.76]
3 [1140.72 1200.73 1260.74 1320.75 1380.76]
Computing regular fft specgram
(5,)
[12002 12002 11995 12002 12002]
[ 60.78  120.79  180.765 240.775 300.785]
4 [1500.78  1560.79  1620.765 1680.775 1740.785]
Computing regular fft specgram
(5,)
[12002 12002 12002 11998 12002]
[ 60.805 120.815 180.825 240.815 300.825]
5 [1860.805 1920.815 1980.825 2040.815 2100.825]
Computing regular fft specgram
(5,)
[12002 11994 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12002]
[120.59 180.6  240.61 300.62]
0 [120.59 180.6  240.61 300.62]
Computing regular fft specgram
(5,)
[12002 12002 12002 11989 12002]
[ 60.64  120.65  180.66  240.605 300.615]
1 [420.64  480.65  540.66  600.605 660.615]
Computing regular fft specgram
(5,)
[11997 12002 11999 12002 12002]
[ 60.61  120.62  180.615 240.625 300.635]
2 [ 780.61   840.62   900.615  960.625 1020.635]
Computing regular fft specgram
(5,)
[11998 11993 12002 12002 12002]
[ 60.635 120.6   180.61  240.62  300.63 ]
3 [1140.635 1200.6   1260.61  1320.62  1380.63 ]
Computing regular fft specgram
(5,)
[12003 12002 12002 12002 12002]
[ 60.63 120.64 180.65 240.66 300.67]
4 [1500.63 1560.64 1620.65 1680.66 1740.67]
Computing regular fft specgram
(5,)
[11998 12002 12002 12002 11998]
[ 60.645 120.655 180.665 240.675 300.665]
5 [1860.645 1920.655 1980.665 2040.675 2100.665]
Computing regular fft specgram
(5,)
[12002 12002 12002 119

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12003 11998 12003 12002]
[120.595 180.585 240.6   300.61 ]
0 [120.595 180.585 240.6   300.61 ]
Computing regular fft specgram
(5,)
[11997 11999 12002 12002 12002]
[ 60.605 120.6   180.61  240.62  300.63 ]
1 [420.605 480.6   540.61  600.62  660.63 ]
Computing regular fft specgram
(5,)
[12002 12002 12003 12002 12002]
[ 60.65  120.66  180.675 240.685 300.695]
2 [ 780.65   840.66   900.675  960.685 1020.695]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 11998]
[ 60.715 120.725 180.72  240.73  300.72 ]
3 [1140.715 1200.725 1260.72  1320.73  1380.72 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 11997 12003]
[ 60.74  120.75  180.76  240.745 300.76 ]
4 [1500.74  1560.75  1620.76  1680.745 1740.76 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.78 120.79 180.8  240.81 300.82]
5 [1860.78 1920.79 1980.8  2040.81 2100.82]
Computing regular fft specgram
(5,)
[12002 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[11998 12002 12002 12002]
[120.56 180.57 240.58 300.59]
0 [120.56 180.57 240.58 300.59]
Computing regular fft specgram
(5,)
[12002 11999 12002 11995 12002]
[ 60.61  120.605 180.615 240.59  300.6  ]
1 [420.61  480.605 540.615 600.59  660.6  ]
Computing regular fft specgram
(5,)
[12002 11999 12002 11998 12002]
[ 60.62  120.615 180.625 240.615 300.625]
2 [ 780.62   840.615  900.625  960.615 1020.625]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 12002]
[ 60.63  120.64  180.635 240.645 300.655]
3 [1140.63  1200.64  1260.635 1320.645 1380.655]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.675 120.685 180.695 240.705 300.715]
4 [1500.675 1560.685 1620.695 1680.705 1740.715]
Computing regular fft specgram
(5,)
[12003 12002 12002 11998 11999]
[ 60.695 120.705 180.715 240.705 300.7  ]
5 [1860.695 1920.705 1980.715 2040.705 2100.7  ]
Computing regular fft specgram
(5,)
[11998 12002

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 11997 12003 12002]
[120.585 180.57  240.585 300.595]
0 [120.585 180.57  240.585 300.595]
Computing regular fft specgram
(5,)
[12002 11999 11997 12002 11998]
[ 60.615 120.61  180.595 240.605 300.595]
1 [420.615 480.61  540.595 600.605 660.595]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.615 120.625 180.635 240.645 300.655]
2 [ 780.615  840.625  900.635  960.645 1020.655]
Computing regular fft specgram
(5,)
[12002 12002 12003 12002 12002]
[ 60.635 120.645 180.66  240.67  300.68 ]
3 [1140.635 1200.645 1260.66  1320.67  1380.68 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 11999 12002]
[ 60.7   120.71  180.72  240.715 300.725]
4 [1500.7   1560.71  1620.72  1680.715 1740.725]
Computing regular fft specgram
(5,)
[12002 12002 12002 11999 11998]
[ 60.745 120.755 180.765 240.76  300.75 ]
5 [1860.745 1920.755 1980.765 2040.76  2100.75 ]
Computing regular fft specgram
(5,)
[120

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12002]
[120.565 180.575 240.585 300.595]
0 [120.565 180.575 240.585 300.595]
Computing regular fft specgram
(5,)
[12002 12003 12002 11997 11999]
[ 60.59  120.605 180.615 240.6   300.595]
1 [420.59  480.605 540.615 600.6   660.595]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 11998]
[ 60.6  120.61 180.62 240.63 300.62]
2 [ 780.6   840.61  900.62  960.63 1020.62]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.64 120.65 180.66 240.67 300.68]
3 [1140.64 1200.65 1260.66 1320.67 1380.68]
Computing regular fft specgram
(5,)
[12002 12002 11993 12002 12002]
[ 60.7   120.71  180.675 240.685 300.695]
4 [1500.7   1560.71  1620.675 1680.685 1740.695]
Computing regular fft specgram
(5,)
[12002 11998 12002 12003 12002]
[ 60.72  120.71  180.72  240.735 300.745]
5 [1860.72  1920.71  1980.72  2040.735 2100.745]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12002]
[120.57 180.58 240.59 300.6 ]
0 [120.57 180.58 240.59 300.6 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 11999 12002]
[ 60.625 120.635 180.645 240.64  300.65 ]
1 [420.625 480.635 540.645 600.64  660.65 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.67 120.68 180.69 240.7  300.71]
2 [ 780.67  840.68  900.69  960.7  1020.71]
Computing regular fft specgram
(5,)
[12002 11999 11998 12002 12002]
[ 60.73  120.725 180.715 240.725 300.735]
3 [1140.73  1200.725 1260.715 1320.725 1380.735]
Computing regular fft specgram
(5,)
[12002 12002 12002 11998 12002]
[ 60.755 120.765 180.775 240.765 300.775]
4 [1500.755 1560.765 1620.775 1680.765 1740.775]
Computing regular fft specgram
(5,)
[12002 11998 11997 12002 12002]
[ 60.77  120.76  180.745 240.755 300.765]
5 [1860.77  1920.76  1980.745 2040.755 2100.765]
Computing regular fft specgram
(5,)
[12003 12002 12002 120

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12002]
[120.58 180.59 240.6  300.61]
0 [120.58 180.59 240.6  300.61]
Computing regular fft specgram
(5,)
[12002 12002 12003 11997 12002]
[ 60.63  120.64  180.655 240.64  300.65 ]
1 [420.63  480.64  540.655 600.64  660.65 ]
Computing regular fft specgram
(5,)
[12002 12002 12003 12002 12002]
[ 60.67  120.68  180.695 240.705 300.715]
2 [ 780.67   840.68   900.695  960.705 1020.715]
Computing regular fft specgram
(5,)
[12002 11999 12002 12002 12002]
[ 60.735 120.73  180.74  240.75  300.76 ]
3 [1140.735 1200.73  1260.74  1320.75  1380.76 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.78 120.79 180.8  240.81 300.82]
4 [1500.78 1560.79 1620.8  1680.81 1740.82]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.845 120.855 180.865 240.875 300.885]
5 [1860.845 1920.855 1980.865 2040.875 2100.885]
Computing regular fft specgram
(5,)
[12002 12002 11999 120

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12003]
[120.565 180.575 240.585 300.6  ]
0 [120.565 180.575 240.585 300.6  ]
Computing regular fft specgram
(5,)
[12002 12002 12002 11999 12002]
[ 60.62  120.63  180.64  240.635 300.645]
1 [420.62  480.63  540.64  600.635 660.645]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.665 120.675 180.685 240.695 300.705]
2 [ 780.665  840.675  900.685  960.695 1020.705]
Computing regular fft specgram
(5,)
[12002 11999 12002 12002 12002]
[ 60.725 120.72  180.73  240.74  300.75 ]
3 [1140.725 1200.72  1260.73  1320.74  1380.75 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.775 120.785 180.795 240.805 300.815]
4 [1500.775 1560.785 1620.795 1680.805 1740.815]
Computing regular fft specgram
(5,)
[12003 12002 12002 12002 12002]
[ 60.815 120.825 180.835 240.845 300.855]
5 [1860.815 1920.825 1980.835 2040.845 2100.855]
Computing regular fft specgram
(5,)
[119

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[11998 12002 12002 12002]
[120.52 180.53 240.54 300.55]
0 [120.52 180.53 240.54 300.55]
Computing regular fft specgram
(5,)
[11998 12002 12002 12002 12002]
[ 60.55 120.56 180.57 240.58 300.59]
1 [420.55 480.56 540.57 600.58 660.59]
Computing regular fft specgram
(5,)
[11993 12002 12002 12002 11998]
[ 60.565 120.575 180.585 240.595 300.585]
2 [ 780.565  840.575  900.585  960.595 1020.585]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.605 120.615 180.625 240.635 300.645]
3 [1140.605 1200.615 1260.625 1320.635 1380.645]
Computing regular fft specgram
(5,)
[11998 12002 12002 12002 12002]
[ 60.645 120.655 180.665 240.675 300.685]
4 [1500.645 1560.655 1620.665 1680.675 1740.685]
Computing regular fft specgram
(5,)
[12003 12002 12002 12002 12002]
[ 60.71 120.72 180.73 240.74 300.75]
5 [1860.71 1920.72 1980.73 2040.74 2100.75]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 11998]


(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12003]
[120.57  180.58  240.59  300.605]
0 [120.57  180.58  240.59  300.605]
Computing regular fft specgram
(5,)
[12002 11998 12003 11998 12002]
[ 60.625 120.615 180.63  240.62  300.63 ]
1 [420.625 480.615 540.63  600.62  660.63 ]
Computing regular fft specgram
(5,)
[12003 12002 11998 12002 12002]
[ 60.655 120.665 180.655 240.665 300.675]
2 [ 780.655  840.665  900.655  960.665 1020.675]
Computing regular fft specgram
(5,)
[12002 11999 12002 12002 12002]
[ 60.675 120.67  180.68  240.69  300.7  ]
3 [1140.675 1200.67  1260.68  1320.69  1380.7  ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12003]
[ 60.72  120.73  180.74  240.75  300.765]
4 [1500.72  1560.73  1620.74  1680.75  1740.765]
Computing regular fft specgram
(5,)
[11997 11998 12002 12002 12002]
[ 60.76 120.75 180.76 240.77 300.78]
5 [1860.76 1920.75 1980.76 2040.77 2100.78]
Computing regular fft specgram
(5,)
[12002 11992 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12002]
[120.585 180.595 240.605 300.615]
0 [120.585 180.595 240.605 300.615]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 11998]
[ 60.62 120.63 180.64 240.65 300.64]
1 [420.62 480.63 540.64 600.65 660.64]
Computing regular fft specgram
(5,)
[11998 12002 12002 12003 12002]
[ 60.64  120.65  180.66  240.675 300.685]
2 [ 780.64   840.65   900.66   960.675 1020.685]
Computing regular fft specgram
(5,)
[12002 12002 11988 12002 12002]
[ 60.705 120.715 180.655 240.665 300.675]
3 [1140.705 1200.715 1260.655 1320.665 1380.675]
Computing regular fft specgram
(5,)
[12003 11998 12003 11992 12003]
[ 60.7   120.69  180.705 240.665 300.68 ]
4 [1500.7   1560.69  1620.705 1680.665 1740.68 ]
Computing regular fft specgram
(5,)
[11998 12002 12003 12002 12002]
[ 60.68  120.69  180.705 240.715 300.725]
5 [1860.68  1920.69  1980.705 2040.715 2100.725]
Computing regular fft specgram
(5,)
[12002 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[11998 12002 12002 11997]
[120.545 180.555 240.565 300.55 ]
0 [120.545 180.555 240.565 300.55 ]
Computing regular fft specgram
(5,)
[12003 11997 12002 12002 11998]
[ 60.575 120.56  180.57  240.58  300.57 ]
1 [420.575 480.56  540.57  600.58  660.57 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 11994 12002]
[ 60.595 120.605 180.615 240.585 300.595]
2 [ 780.595  840.605  900.615  960.585 1020.595]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 12002]
[ 60.615 120.625 180.62  240.63  300.64 ]
3 [1140.615 1200.625 1260.62  1320.63  1380.64 ]
Computing regular fft specgram
(5,)
[11998 12002 12002 12003 12002]
[ 60.615 120.625 180.635 240.65  300.66 ]
4 [1500.615 1560.625 1620.635 1680.65  1740.66 ]
Computing regular fft specgram
(5,)
[11998 12003 12002 12002 12002]
[ 60.66  120.675 180.685 240.695 300.705]
5 [1860.66  1920.675 1980.685 2040.695 2100.705]
Computing regular fft specgram
(5,)
[120

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12003 12002 12002]
[120.565 180.58  240.59  300.6  ]
0 [120.565 180.58  240.59  300.6  ]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 11999]
[ 60.595 120.605 180.6   240.61  300.605]
1 [420.595 480.605 540.6   600.61  660.605]
Computing regular fft specgram
(5,)
[12002 12003 12002 12002 12002]
[ 60.6   120.615 180.625 240.635 300.645]
2 [ 780.6    840.615  900.625  960.635 1020.645]
Computing regular fft specgram
(5,)
[12002 12002 11998 12002 11982]
[ 60.665 120.675 180.665 240.675 300.585]
3 [1140.665 1200.675 1260.665 1320.675 1380.585]
Computing regular fft specgram
(5,)
[12002 11999 12002 12002 12002]
[ 60.605 120.6   180.61  240.62  300.63 ]
4 [1500.605 1560.6   1620.61  1680.62  1740.63 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.65 120.66 180.67 240.68 300.69]
5 [1860.65 1920.66 1980.67 2040.68 2100.69]
Computing regular fft specgram
(5,)
[12002 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 11998]
[120.555 180.565 240.575 300.565]
0 [120.555 180.565 240.575 300.565]
Computing regular fft specgram
(5,)
[12002 12003 12002 12002 11999]
[ 60.565 120.58  180.59  240.6   300.595]
1 [420.565 480.58  540.59  600.6   660.595]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.615 120.625 180.635 240.645 300.655]
2 [ 780.615  840.625  900.635  960.645 1020.655]
Computing regular fft specgram
(5,)
[12002 12002 11999 12002 12002]
[ 60.675 120.685 180.68  240.69  300.7  ]
3 [1140.675 1200.685 1260.68  1320.69  1380.7  ]
Computing regular fft specgram
(5,)
[12002 12002 12002 11999 12002]
[ 60.72  120.73  180.74  240.735 300.745]
4 [1500.72  1560.73  1620.74  1680.735 1740.745]
Computing regular fft specgram
(5,)
[11999 11999 12002 11998 12002]
[ 60.75  120.745 180.755 240.745 300.755]
5 [1860.75  1920.745 1980.755 2040.745 2100.755]
Computing regular fft specgram
(5,)
[120

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12003 12002 12002 11993]
[120.565 180.575 240.585 300.55 ]
0 [120.565 180.575 240.585 300.55 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 11999]
[ 60.57  120.58  180.59  240.6   300.595]
1 [420.57  480.58  540.59  600.6   660.595]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.615 120.625 180.635 240.645 300.655]
2 [ 780.615  840.625  900.635  960.645 1020.655]
Computing regular fft specgram
(5,)
[12002 12003 11994 12002 12002]
[ 60.675 120.69  180.66  240.67  300.68 ]
3 [1140.675 1200.69  1260.66  1320.67  1380.68 ]
Computing regular fft specgram
(5,)
[12002 12003 12002 12002 12002]
[ 60.7   120.715 180.725 240.735 300.745]
4 [1500.7   1560.715 1620.725 1680.735 1740.745]
Computing regular fft specgram
(5,)
[11999 12002 12002 12002 12002]
[ 60.75 120.76 180.77 240.78 300.79]
5 [1860.75 1920.76 1980.77 2040.78 2100.79]
Computing regular fft specgram
(5,)
[12002 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12003 12002]
[120.52  180.53  240.545 300.555]
0 [120.52  180.53  240.545 300.555]
Computing regular fft specgram
(5,)
[12002 12003 12002 11994 11998]
[ 60.555 120.57  180.58  240.55  300.54 ]
1 [420.555 480.57  540.58  600.55  660.54 ]
Computing regular fft specgram
(5,)
[12003 12002 12002 11997 12002]
[ 60.565 120.575 180.585 240.57  300.58 ]
2 [ 780.565  840.575  900.585  960.57  1020.58 ]
Computing regular fft specgram
(5,)
[12003 12002 11995 12002 12002]
[ 60.605 120.615 180.59  240.6   300.61 ]
3 [1140.605 1200.615 1260.59  1320.6   1380.61 ]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 12002]
[ 60.61 120.62 180.63 240.64 300.65]
4 [1500.61 1560.62 1620.63 1680.64 1740.65]
Computing regular fft specgram
(5,)
[12002 12002 12002 12002 11998]
[ 60.655 120.665 180.675 240.685 300.675]
5 [1860.655 1920.665 1980.675 2040.685 2100.675]
Computing regular fft specgram
(5,)
[12002 12002 1

(1382400000,)
<class 'numpy.float32'>
Computing regular fft specgram
(4,)
[12002 12002 12002 12002]
[120.585 180.595 240.605 300.615]
0 [120.585 180.595 240.605 300.615]
Computing regular fft specgram
(5,)
[12002 12002 12002 11999 12002]
[ 60.635 120.645 180.655 240.65  300.66 ]
1 [420.635 480.645 540.655 600.65  660.66 ]
Computing regular fft specgram
(5,)
[11998 12003 12002 12002 12002]
[ 60.64  120.655 180.665 240.675 300.685]
2 [ 780.64   840.655  900.665  960.675 1020.685]
Computing regular fft specgram
(5,)
[12002 11994 12002 12002 12002]
[ 60.705 120.675 180.685 240.695 300.705]
3 [1140.705 1200.675 1260.685 1320.695 1380.705]
Computing regular fft specgram
(5,)
[11999 12002 12002 12002 11998]
[ 60.71 120.72 180.73 240.74 300.73]
4 [1500.71 1560.72 1620.73 1680.74 1740.73]
Computing regular fft specgram
(5,)
[12002 12002 11998 12002 12002]
[ 60.73 120.74 180.73 240.74 300.75]
5 [1860.73 1920.74 1980.73 2040.74 2100.75]
Computing regular fft specgram
(5,)
[12002 12002 12002 12003

In [3]:
# np.save('/home/cat/times_3600.npy', times)


In [6]:
print (times)

[array([ 5.545, 30.545, 55.525]), array([ 5.555, 30.52 , 55.52 ]), array([ 5.53 , 30.535, 55.515]), array([ 5.575, 30.575, 55.58 ]), array([ 5.55 , 30.555, 55.56 ]), array([ 5.555, 30.56 , 55.565]), array([ 5.57 , 30.55 , 55.555]), array([ 0.38 ,  5.53 , 30.535, 55.525]), array([ 5.535, 30.54 , 55.545]), array([ 5.555, 30.56 , 55.565]), array([ 5.565, 30.545, 55.535]), array([ 5.57 , 30.575, 55.58 ]), array([ 5.54 , 30.53 , 55.535]), array([ 5.57 , 30.575, 55.555]), array([ 5.56 , 30.565, 55.565]), array([ 5.565, 30.57 , 55.575]), array([ 5.555, 30.535, 55.54 ]), array([ 5.55 , 30.555, 55.545]), array([ 5.58 , 30.57 , 55.575]), array([ 5.545, 30.55 , 55.555]), array([ 5.57 , 30.555, 55.56 ]), array([ 5.555, 30.56 , 55.56 ]), array([ 5.55 , 30.555, 55.56 ]), array([ 5.57 , 30.575, 55.58 ]), array([ 5.555, 30.56 , 55.54 ]), array([ 5.555, 30.56 , 55.545]), array([ 5.565, 30.57 , 55.575]), array([ 5.58 , 30.585, 55.59 ]), array([ 5.545, 30.55 , 55.55 ]), array([ 5.575, 30.575, 55.58 ]), a

In [16]:
times1D = np.hstack(times)
print (times1D)

y = np.histogram(times1D, np.arange(0,60,0.010))
ax=plt.subplot(3,1,1)
#plt.bar(y[1][:-1], y[0],0.009)
plt.plot(y[1][:-1], y[0])
plt.xlim(5,6)
plt.ylabel("5sec beep",fontsize=20)

ax=plt.subplot(3,1,2)
#plt.bar(y[1][:-1], y[0],0.009)
plt.plot(y[1][:-1], y[0])
plt.xlim(30,31)
plt.ylabel("30sec beep",fontsize=20)

ax=plt.subplot(3,1,3)
plt.plot(y[1][:-1], y[0])
plt.xlim(55,56)
plt.ylabel("55sec beep",fontsize=20)
plt.xlabel("Time (sec)", fontsize=20)
plt.show()

[ 5.545 30.545 55.525  5.555 30.52  55.52   5.53  30.535 55.515  5.575
 30.575 55.58   5.55  30.555 55.56   5.555 30.56  55.565  5.57  30.55
 55.555  0.38   5.53  30.535 55.525  5.535 30.54  55.545  5.555 30.56
 55.565  5.565 30.545 55.535  5.57  30.575 55.58   5.54  30.53  55.535
  5.57  30.575 55.555  5.56  30.565 55.565  5.565 30.57  55.575  5.555
 30.535 55.54   5.55  30.555 55.545  5.58  30.57  55.575  5.545 30.55
 55.555  5.57  30.555 55.56   5.555 30.56  55.56   5.55  30.555 55.56
  5.57  30.575 55.58   5.555 30.56  55.54   5.555 30.56  55.545  5.565
 30.57  55.575  5.58  30.585 55.59   5.545 30.55  55.55   5.575 30.575
 55.58   5.55  30.55  55.555  5.58  30.585 55.57   5.555 30.555 55.54
  5.53  30.535 55.54   5.535 30.54  55.545  5.55  30.555 55.54   5.575
 30.58  55.585  5.57  30.575 55.555  5.57  30.575 55.575  5.555 30.56
 55.56   5.565 30.57  55.545  5.565 30.57  55.575  5.55  30.555 55.56
  5.545 30.55  55.555  5.55  30.555 53.275 55.505  5.54  30.545 38.035
 55.53   5.55

In [ ]:
for k in range(3):
    temp= times_array[:,0]
    print (temp)
    y = np.histogram(temp, np.ar
    

In [16]:
# visualize audio
print ("rec: ", audio_rec.shape)

P, extent = Specgram(data = audio_rec.squeeze(), sampfreq = 384000, 
                     p0=-300, f0=0.1, f1=384000, 
                     width=0.01, tres = 0.005)

print (P.shape, extent)
plt.imshow(P,extent=extent, aspect='auto')
plt.xlabel("Time (sec)", fontsize=20)
plt.show()


rec:  (23040000, 1)
Computing regular fft specgram
(1920, 11999) (0.0, 59.99999739583333, 100.0, 192000.0)


In [17]:
data = P #[:1920,:120000]
rec_len = 60

print (data.sum(0).mean())
data = data.sum(0)-data.sum(0).mean(0)

scale = P.shape[1]/200.
t=np.arange(P.shape[1])/200.

# find peaks
thresh = 18000
idx = np.where(data>thresh)[0]
idx_corrected=[]
idx_corrected.append(idx[0])
for k in range(1, idx.shape[0], 1):
    if idx[k]-idx[k-1]>5:
        idx_corrected.append(idx[k])
    
idx = np.array(idx_corrected)
#print (idx)

# find peaks that different various amounts
diffs = idx[1:]-idx[:-1]
print (diffs.shape)

# look for thresholds that are bigger than some minmum width; 
idx2 = np.where(np.logical_and(diffs!=200,diffs>3,diffs!=199))[0]
print (diffs[idx2])

ax=plt.subplot(211)
plt.plot(t, data)
#plt.plot([0,119999/200.],[thresh,thresh],c='red')
for id_ in idx_corrected:
    plt.plot([id_/200.,id_/200.],[0,30000],c='green')
for id_ in idx[idx2+1]:
    plt.plot([id_/200.,id_/200.],[0,30000],c='red')

# manually define a new patch 
#patch = mpatches.Patch(color='grey', label='1sec beep')
#labels.append(patch) 
#plt.legend(handles=labels, loc='upper center')
print (idx[idx2+1]/200.)

#plt.title()

ax=plt.subplot(212)
y = np.histogram(diffs, bins = np.arange(10,400,.001))
plt.plot(y[1][:-1]/scale,y[0])
ax.set_yscale('log')
#plt.title("600 second audio recording of 1sec beeps", fontsize=20)
plt.xlabel("Inter-beep interval distributions (seconds)",fontsize=20)
plt.ylabel("# of frames apart by x-axis amount",fontsize=20)
plt.show()

-328144.05501826375
(3,)
[ 307 5797 5001]
[ 1.535 30.52  55.525]


In [ ]:
-328144.05501826375
(3,)
[ 307 5797 5001]
[ 1.535 30.52  55.525]

-328619.41143776797
(3,)
[ 291 5767 4993]
[ 1.455 30.29  55.255]
